name: tagpr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      tagpr-tag: ${{ steps.run-tagpr.outputs.tag }}
    permissions:
      contents: write
      pull-requests: write
      issues: write
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - id: run-tagpr
        name: Run tagpr
        uses: Songmu/tagpr@v1

  release:
    needs: tagpr
    if: needs.tagpr.outputs.tagpr-tag != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v6
      - uses: cli/gh-extension-precompile@v2
        with:
          generate_attestations: true
          release_tag: ${{ needs.tagpr.outputs.tagpr-tag }}
          go_version_file: go.mod
      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.tagpr.outputs.tagpr-tag }}
          files: dist/*
